// Code generated by MockGen. DO NOT EDIT.
// Source: stores.go
//
// Generated by this command:
//
//	mockgen -source=stores.go -destination=./mock/stores.go
//

// Package mock_stores is a generated GoMock package.
package mock_stores

import (
	categories "arox-products/internal/stores/categories"
	images "arox-products/internal/stores/images"
	products "arox-products/internal/stores/products"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockStores is a mock of Stores interface.
type MockStores struct {
	ctrl     *gomock.Controller
	recorder *MockStoresMockRecorder
	isgomock struct{}
}

// MockStoresMockRecorder is the mock recorder for MockStores.
type MockStoresMockRecorder struct {
	mock *MockStores
}

// NewMockStores creates a new mock instance.
func NewMockStores(ctrl *gomock.Controller) *MockStores {
	mock := &MockStores{ctrl: ctrl}
	mock.recorder = &MockStoresMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStores) EXPECT() *MockStoresMockRecorder {
	return m.recorder
}

// Categories mocks base method.
func (m *MockStores) Categories() categories.Store {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Categories")
	ret0, _ := ret[0].(categories.Store)
	return ret0
}

// Categories indicates an expected call of Categories.
func (mr *MockStoresMockRecorder) Categories() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Categories", reflect.TypeOf((*MockStores)(nil).Categories))
}

// Images mocks base method.
func (m *MockStores) Images() images.Store {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Images")
	ret0, _ := ret[0].(images.Store)
	return ret0
}

// Images indicates an expected call of Images.
func (mr *MockStoresMockRecorder) Images() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Images", reflect.TypeOf((*MockStores)(nil).Images))
}

// Products mocks base method.
func (m *MockStores) Products() products.Store {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Products")
	ret0, _ := ret[0].(products.Store)
	return ret0
}

// Products indicates an expected call of Products.
func (mr *MockStoresMockRecorder) Products() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Products", reflect.TypeOf((*MockStores)(nil).Products))
}
